# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/new_single_synchronisation/new_single_synchronisation.srcs/sources_1/ip/IMU_fifo/IMU_fifo.xci
# IP: The module: 'IMU_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/new_single_synchronisation/new_single_synchronisation.gen/sources_1/ip/IMU_fifo/IMU_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMU_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/new_single_synchronisation/new_single_synchronisation.gen/sources_1/ip/IMU_fifo/IMU_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMU_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/new_single_synchronisation/new_single_synchronisation.srcs/sources_1/ip/IMU_fifo/IMU_fifo.xci
# IP: The module: 'IMU_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/new_single_synchronisation/new_single_synchronisation.gen/sources_1/ip/IMU_fifo/IMU_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMU_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/new_single_synchronisation/new_single_synchronisation.gen/sources_1/ip/IMU_fifo/IMU_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'IMU_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
