# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.runs/synth_1/top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.cache/wt [current_project]
set_property parent.project_path D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/Dual_FF_Synchroniser.sv
read_verilog -library xil_defaultlib {
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/Demux8.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/EM_Controller.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/IMU_Fifo_Controller.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/IMU_SPI_Driver.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/Mux8.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/SPI_Master_With_Single_CS.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/SPI_driver.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/Timestamp_Generator.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/UART_Controller.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/UART_TX.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/lut_256.v
  D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/new/top.v
}
read_ip -quiet D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/sources_1/ip/IMU_fifo/IMU_fifo.xci
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/IMU_fifo/IMU_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.gen/sources_1/ip/IMU_fifo/IMU_fifo_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/new_single_synchronisation_with_EM_new_sensor/Nexys-Video-Master.xdc
set_property used_in_implementation false [get_files D:/new_single_synchronisation_with_EM_new_sensor/Nexys-Video-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental D:/new_single_synchronisation_with_EM_new_sensor/new_single_synchronisation.srcs/utils_1/imports/synth_1/top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
